defaults: &defaults
  adapter: postgresql
  host: localhost

development:
  <<: *defaults
  database: rinterview_development

production:
  <<: *defaults
  database: rinterview_production

test:
  <<: *defaults
  database: rinterview_test